# Generated by Django 4.1.4 on 2022-12-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("address", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=13)),
                (
                    "order",
                    models.CharField(
                        choices=[
                            ("In our hall", "In our hall"),
                            ("Catering", "Catering"),
                            ("Stylized holidays", "Stylized holidays"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
