# Generated by Django 4.1.4 on 2022-12-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aboutpage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Mainpain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Orderpage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagephone", models.ImageField(upload_to="")),
                ("number", models.TextField()),
                ("address", models.URLField(max_length=100)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Servicepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
