# Generated by Django 4.1.4 on 2022-12-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_aboutpage_mainpain_orderpage_servicepage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mainpain",
            new_name="Mainpage",
        ),
    ]
