# Generated by Django 4.1.4 on 2022-12-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_mainpain_mainpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mainpage",
        ),
        migrations.AddField(
            model_name="events",
            name="image_background",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
