# Generated by Django 4.1.4 on 2022-12-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_delete_mainpage_events_image_background"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="image_background",
        ),
    ]
