# Generated by Django 4.1.4 on 2022-12-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_mainpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpage",
            name="address",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
