# Generated by Django 4.1.4 on 2022-12-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_orderpage_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpage",
            name="address",
            field=models.TextField(null=True),
        ),
    ]
